config/routes.rb
Challenger::Application.routes.draw do
  resources :users
  resources :challenges
  resources :participations

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
has_many :participations
has_many :users, through: :participations

end

app/models/participation.rb
class Participation < ActiveRecord::Base
belongs_to :challenge
belongs_to :user
  validates :challenge_id, presence: true



end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :participations
  has_many :challenges, through: :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
    logger.debug '*'*99
    @participations = @challenge.participations
    @participation = @challenge.participations.new
    @users = @challenge.users

  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render action: 'show', status: :created, location: @challenge }
      else
        format.html { render action: 'new' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:title, :description, :expires_at, :points)
    end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def create
    @participation = Participation.new(participation_params)

  if @participation.save
    redirect_to @participation.challenge, notice:'Participation was succesfull updated.'
  else
    render text:'Error !'
  end

  end

  private

  def participation_params
    params.require(:participation).permit(:user_id, :message,:challenge_id )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @challenges = @user.challenges
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/challenges/_challenge.html.erb
<div    class="challenge">
  <h4> <%=	 challenge.title %></h4 >
  <p><%=	 challenge.description %></p>



</div>

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :expires_at %><br>
    <%= f.datetime_select :expires_at %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.number_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/_participations.html.erb
<hr/>
<h2>Participations</h2>
<ul>
  <%= render @participations %>
</ul>
<hr/>

app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<h1>Listing challenges</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Expires at</th>
      <th>Points</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= link_to challenge.title, challenge %></td>
        <td><%= challenge.description %></td>
        <td><%= challenge.expires_at %></td>
        <td><%= challenge.points %></td>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @challenge.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @challenge.description %>
</p>

<p>
  <strong>Expires at:</strong>
  <%= @challenge.expires_at %>
</p>

<p>
  <strong>Points:</strong>
  <%= @challenge.points %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>

<hr />
<h1>Participants</h1>
<%=	 render @users %>

<hr />
<%=	 render 'participations' %>
<hr />
<h2>Nouvelle participation</h2>

<%=	 render 'participations/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Challenger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/participations/_form.html.erb
<%= form_for @participation do |f| %>
    <%= f.hidden_field :challenge_id %>
    <br>
    <%= f.text_field :user_id, :placeholder => 'user_id' %>
    <br>
    <%= f.text_area :message %>
    <br>
    <%= f.submit %>

<% end %>

app/views/participations/_participation.html.erb
 <li>
   <%= participation.user_id %><br>
   <%= participation.message %>
 </li>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="user">
     <%= user.name %>
  <img src="http://www.gravatar.com/avatar/4156423<%= user.id %>?d=monsterid&s=50">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<hr>
<h1>Ses challenges</h1>
<%= render @challenges   %>